### PR TITLE
Fix for broken build in xcode 9.1 (swift 4).

### PR DESCRIPTION
**Pull request by corabius**
This fix was not present in the awaiting pull-request #21. Restofire was not building for me on xcode 9.1 running swift 4.

### CODE REVIEW

**Comment by rahul0x24** [comment]
You can use the version v2.3.0 for now which includes Swift 3.2, It can coexist with Swift 4 code :).
This change will be included in next release when the library is updated for Swift 4.

**Comment by ciryon** [comment]
I still have this compilation error in version 2.3.0.

**Comment by rahul0x24** [comment]
I will make a new release 2.4.0 with this change 👍🏻
Thanks for contributing.
